# Generated by Django 5.2.6 on 2025-09-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconceptprogress',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userconceptprogress',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
